stages:
  - build
  - deploy

variables:
  S3_BUCKET_NAME: "www.ericdudley.com"

build-dist:
  stage: build
  image: node
  script:
    - echo "Getting dependencies..."
    - npm install
    - echo "Building dist..."
    - npm run build
    - npm run build-sitemap
    - mv sitemap.xml dist
    - mv sitemap-0.xml dist
    - echo "Adding ci stamp..."
    - echo "<!-- Built and deployed with GitLab CI. Build $CI_JOB_ID for project $CI_PROJECT_NAME. Git url $CI_REPOSITORY_URL Commit $CI_COMMIT_SHA -->$(cat dist/index.html)" > dist/index.html
  artifacts:
    paths:
      - "dist"
  cache:
    untracked: true

deploy-image-prod:
  stage: deploy
  image: mesosphere/aws-cli
  script:
    - aws s3 cp ./dist s3://$S3_BUCKET_NAME/ --recursive --include "*"
  environment:
    name: production
    url: http://www.ericdudley.com
  only: 
    - master

deploy-image-staging:
  stage: deploy
  image: alpine
  script:
    - mkdir -p ./public
    - rsync -r ./dist ./public
  environment:
    name: staging
    url: http://ericdudley.gitlab.io/personal-website/
  except: 
    - master