image: node:alpine

stages:
  - build

build-dist:
  stage: build
  script:
    - echo "Getting dependencies..."
    - npm install
    - echo "Building dist..."
    - npm run build
    - npm run build-sitemap
    - mv sitemap.xml dist
    - mv sitemap-0.xml dist
    - echo "Adding ci stamp..."
    - echo "<!-- Built and deployed with GitLab CI. Build $CI_JOB_ID for project $CI_PROJECT_NAME. Git url: $CI_REPOSITORY_URL Commit: $CI_COMMIT_SHA -->$(cat dist/index.html)" > dist/index.html
    - echo "Building docker image..."
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/ericdudley/personal-website .
    - docker push registry.gitlab.com/ericdudley/personal-website